stratinum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from imagec import views as imagec_views
from contact import views as contact_views

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', imagec_views.home, name='home'),
    url(r'^signup1/$', imagec_views.signup1, name='signup1'),
    url(r'^profile/$', imagec_views.userProfile, name='profile'),
    url(r'^contact/$', contact_views.contact, name='contact'),
    url(r'^post/$', imagec_views.post_detail, name='post_detail'),
    url(r'^post/new/$', imagec_views.post_new, name='post_new'),
    url(r'^post/edit/$', imagec_views.post_edit, name='post_edit'),
    url(r'^accounts/', include('allauth.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^newhome/$', imagec_views.newhome, name='newhome'),
    url(r'^create_form/$', imagec_views.create_form, name='create_form'),
    url(r'^profile/edit/$', imagec_views.edit_profile, name='edit_profile'),
    url(r'^about/$', imagec_views.about, name='about'),



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

imagec/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import Permission, User

# Create your models here.
class profile(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField(default='description default text')

    def __unicode__(self):
        return self.name

class Post(models.Model):
    user = models.OneToOneField(User)
    Penname = models.CharField(max_length=200)
    AboutMe = models.CharField(max_length=200)
    def __str__(self):
        return self.Penname


class Album(models.Model):
    user = models.OneToOneField(User)
    image = models.FileField()

contact/forms.py
from django import forms

class contactForm(forms.Form):
    name = forms.CharField(required=False, max_length=100, help_text='100 charcter max')
    email = forms.EmailField(required=True)
    comment = forms.CharField(required=True, widget=forms.Textarea)

imagec/forms.py
from django import forms
from .models import Album
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import	Post

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['image']

#from .models import User


class EditProfileForm(UserChangeForm):
    template_name = '/something/else'

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'password'

        )


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('Penname','AboutMe')

contact/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings
from .forms import contactForm

# Create your views here.
def contact(request):
    title = 'Contact'
    form = contactForm(request.POST or None)
    confirm_message = None

    if form.is_valid():
        name = form.cleaned_data['name']
        comment = form.cleaned_data['comment']
        subject = 'Message from MYSITE.com'
        message = '%s %s' %(comment, name)
        emailFrom = form.cleaned_data['email']
        emailTo = [settings.EMAIL_HOST_USER]
        send_mail(subject, message, emailFrom, emailTo, fail_silently=True)
        title = "Thanks!"
        confirm_message = "Thanks for the message. We will get right back to you."
        form = None

    context = {'title':title, 'form':form, 'confirm_message':confirm_message,}
    template = 'contact.html'
    return render(request, template, context)

imagec/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from django.shortcuts import render, get_object_or_404
from .forms import PostForm,AlbumForm,EditProfileForm
from .models import Post
from django.shortcuts import redirect
from django.core.urlresolvers import reverse

# Create your views here.
def home(request):
    context = {}
    template = 'home.html'
    return render(request, template, context)

@login_required
def newhome(request):
    user = request.user
    return render(request, 'newhome.html', {'user': user})


def signup1(request):
    context = {}
    template = 'signup1.html'
    return render(request, template, context)


@login_required()
def userProfile(request):
    user = request.user
    context = {'user': user}
    template = 'profile.html'
    return render(request, template, context)


def about(request):
    context = {}
    template = 'about.html'
    return render(request, template, context)


@login_required()
def create_form(request):
        form = AlbumForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            album = form.save(commit=False)
            album.user = request.user
            album.image= request.FILES['image']
            album.save()
            return render(request, 'about.html', {'album': album})
        context = {
            "form": form,
        }
        return render(request, 'create_form.html', context)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('about'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'edit_profile.html', args)


@login_required
def post_detail(request):
    user = request.user
    return render(request, 'post_detail.html', {'user': user})



@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('newhome')
    else:
        form = PostForm()
    return render(request, 'post_edit.html', {'form': form})



@login_required
def post_edit(request):
    post = get_object_or_404(Post)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            user = request.user
            return render(request, 'newhome.html', {'user': user})
    else:
        form = PostForm(instance=post)
    return render(request, 'newhome.html', {'form': form})

contact/templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{%	block	content	%}
<div class="row">
        <div class="col-xs-4">
<h1>{{ title }}</h1>
{% if confirm_message %}
<p> {{ confirm_message }}</p>
{% endif %}

{% if form %}
<form method="POST" action=""> {% csrf_token %}
{{ form|crispy }}
        <input type="submit" value="submit form" class="btn btn-default"/>
</form>
{% endif %}
</div>
</div>
{%	endblock	%}



imagec/templates/about.html
{% extends 'base.html' %}

{%	block	content	%}
<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>Email: {{ user.email }}</p>
            {% if user.album.image %}
                            <img src="{{ user.album.image.url }}" class="img-responsive">

                         {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
     <div>
               {% if user.is_authenticated %}

         <h1>{{	user.post.Penname	}}</h1>
         <p>{{user.post.AboutMe|linebreaksbr}}</p>

					<a	class="btn	btn-default" href="{% url 'post_edit'	%}"><span	class="glyphicon	glyphicon-pencil"></span></a>
{% endif %}



				</div>

</div>
{%	endblock	%}




imagec/templates/base.html
{%	load	staticfiles	%}


<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Stratinium</title>


       <link rel='stylesheet prefetch' href='http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css'>


    <link href="{%	static	'sociallink.css'	%}" rel="stylesheet">
     <link href="{%	static	'w3.css'	%}" rel="stylesheet">
     <link href="{%	static	'css/pagescroll.css'	%}" rel="stylesheet">
    <!-- <link href="{%	static	'style.css'	%}" rel="stylesheet">-->
      <link href="{%	static	'css1/style.css'	%}" rel="stylesheet">
      <link href="{%	static	'css2/style.css'	%}" rel="stylesheet">
      <link href="{%	static	'css/buttons.css'	%}" rel="stylesheet">

      <link href="{%	static	'css/signup.css'	%}" rel="stylesheet">

       <link href="{%	static	'img_scroll/animation.css'	%}" rel="stylesheet">
       <link href="{%	static	'img_scroll/reset.css'	%}" rel="stylesheet">
       <link href="{%	static	'img_scroll/style.css'	%}" rel="stylesheet">





      <style type="text/css">

	   * { margin: 0; padding: 0; }
	   p { padding: 10px; }
	   #left { position: absolute; left: 0; top: 60px; width: 50%; }
	   #right { position: absolute; right: 20px; top: 200px; width: 50%; }

	   #left1 { position: absolute; left: 0; top: 200px; width: 50%; }
	   #right1{ position: absolute; right: 20px; top: 60px; width: 50%; }




	</style>

       </head>

  <body>




          {%	block	content	%}
          {%	endblock	%}

          {% block body %}
          {%	endblock	%}





    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="{%	static	'javascript/jquery-1.11.3.min.js'	%}"></script>
    <script src="{%	static	'javascript/PageScroll.js'	%}"></script>
    <script src="{%	static	'javascript/jquery.dropotron-1.0.js'	%}"></script>
    <script src="{%	static	'javascript/jquery.slidertron-1.1.js'	%}"></script>
      <!--<script src="{%	static	'javascript/1.js'	%}"></script>-->
      <script src="{%	static	'javascript/2.js'	%}"></script>
  <script src="{%	static	'javascript/index.js'	%}"></script>



  </body>
</html>

imagec/templates/create_form.html
 {% extends 'base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
    <!-- List of uploaded documents -->

   <form action=" " method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

 {% endblock %}

imagec/templates/edit_profile.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

imagec/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}






{%	block	content	%}


    <div class="w3-container">


  <div id="id02" class="w3-modal">

      <div class="w3-center"><br>
        <span onclick="document.getElementById('id02').style.display='none'" class="w3-closebtn w3-hover-red w3-container w3-padding-8 w3-display-topright" title="Close Modal">&times;</span>

      </div>

      <form class="login" method="POST" action="{% url 'account_login' %}">
        {% csrf_token %}



<div class="wrap">
		<div class="avatar">
      <img src="{% static 'img/qt_logo.jpg' %}">
		</div>


	<form class="form-signin">


		<div id="div_id_login" class="form-group">
		<div class="controls">

      <input type="email" class="textinput textInput form-control" id="id_login" name="login" placeholder="Email or Mobile number" required="" autofocus="" />
			<label class="forgot_link1">
      <input id="option" class="form-check-input" type="checkbox" name="field" value="option">
    </label>&nbsp;<a class="forgot_link2">remember</a></div></div>

		<div id="div_id_password" class="form-group">

      <input type="password" class="form-control" name="password" placeholder="Password" required="" autofocus="" />
			<a href="{% url 'account_reset_password' %}" class="forgot_link">forgot ?</a></div>
	</br>
<center>
 <button class="btn btn-lg btn-primary btn-block" type="submit">Sign In</button></center>

	</form>

        <div class="set-1">

            <ul><br>
			</br>
				<h2><font size="3px">OR</font></h2>

            <li><a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}" class="twitter-small">Twitter</a></li>
            <li><a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}" class="facebook-small">Facebook</a></li>
            <li><a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}" class="gplus-small">GPlus</a></li>
</center>

			</ul>

            </div>
		  <p> <font size="2.5"> Don't have an account?<a class="signup_link" href="#signid">SignUP</a></font></p>

</form>


    </div>
  </div>
</div>


<div id="container">
	<div class="sections">
		<div class="section section-1">
	 <div id="wrapper">

	<div class="container1">
	<div id="content-slider">
    	<div id="slider">
        	<div id="mask">
            <ul>
           	<li id="first" class="firstanimation">
            <a href="#">
            <img src="{% static 'img/img_5.jpg' %}" alt="" >

            </a>

            </li>

            <li id="second" class="secondanimation">
            <a href="#">
             <img src="{% static 'img/img_1.jpg' %}" alt="" >
            </a>

            </li>

            <li id="third" class="thirdanimation">
            <a href="#">
            <img src="{% static 'img/img_2.jpg' %}" alt="" >
            </a>

            </li>

            <li id="fourth" class="fourthanimation">
            <a href="#">
             <img src="{% static 'img/img_3.jpg' %}" alt="" >
            </a>

            </li>

            <li id="fifth" class="fifthanimation">
            <a href="#">
             <img src="{% static 'img/img_4.jpg' %}" alt="" >
            </a>

            </li>
            </ul>
            </div>
            <div class="progress-bar"></div>
        </div>
    </div>
</div>

		 </br>

		 {% if not request.user.is_authenticated %}

           <br class="l-2 right">

		   </br>
			   <button onclick="document.getElementById('id02').style.display='block'" class="action-button shadow animate blue" >Login</button>
		 &nbsp;

			 <a class="action-button shadow animate blue"  href="#signid">Signup</a>



                {% else %}
		 </br>
            </br>
                <a href="{% url 'account_logout' %}">Logout</a>
                {% endif %}







 </br>
            </br>

         </br>
            </br>




</div>

</div>
		<div class="section section-2">
			 <img src="{% static 'img/qt.png' %}" alt="" width="46" height="46" align="left" hspace="5vm">
			<!-- ABOUT US -->
          <div id="left">
         <img src="{% static 'img/about.jpg' %}" alt="" width="600" height="600" vspace="100" >
    </div>

    <div id="right">
        <p>About QT</p>
       <p><font size="3">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
		   Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.
		   Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est.
		   Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra.
		   Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi.
		   Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui.
	   </font>
	   </p>

    </div>

		</div>

		<div class="section section-3">
<img src="{% static 'img/qt.png' %}" alt="" width="46" height="46" align="left">

			   <div id="right1">
         <img src="{% static 'img/about.jpg' %}" alt="" width="600" height="600" vspace="100" >
    </div>

    <div id="left1">
        <p>How QT Works</p>
       <p><font size="3">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
		   Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.
		   Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est.
		   Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra.
		   Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi.
		   Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui.
	   </font>
	   </p>

    </div>


		</div>

		<div class="section section-4" id="signid">
<img src="{% static 'img/qt.png' %}" alt="" width="46" height="46" align="left">


{% load crispy_forms_tags %}

{% load i18n %}


<div class="wrapper2">
<form class="form-signin" id="signup_form" method="post" action="{% url 'account_signup' %}">
  <h1 class="form-signin-heading"><center></center></h1>

  <input name="csrfmiddlewaretoken" value="Y72toDc0YUeAMoFgmw7jRGv8uPWsj0093f0QF50kqghzUDFnuSGNrKwRUHAWvNMl" type="hidden">


<div id="div_id_username" class="form-group">

	<div class="controls ">
		<input autofocus="autofocus" class="textinput textInput form-control" id="id_username" maxlength="150" minlength="5" name="username" placeholder="Username" required="" type="text"> </div> </div> <div id="div_id_email" class="form-group">

	<div class="controls ">
		<input class="textinput textInput form-control" id="id_email" name="email" placeholder="E-mail address" required="" type="email"> </div> </div> <div id="div_id_password1" class="form-group">

	<div class="controls ">
		<input class="textinput textInput form-control" id="id_password1" name="password1" placeholder="Password" required="" type="password"> </div> </div> <div id="div_id_password2" class="form-group">

	<div class="controls ">
		<input class="textinput textInput form-control" id="id_password2" name="password2" placeholder="Password (again)" required="" type="password"> </div> </div>


  <button type="submit" class="btn btn-lg btn-primary btn-block">Sign Up</button>



	 <div class="set-1">
			</br>
		 <h2><font size="3px">OR</font></h2>

            <ul><center>

            <li><a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}" class="twitter-small">Twitter</a></li>
            <li><a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}" class="facebook-small">Facebook</a></li>
            <li><a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}" class="gplus-small">GPlus</a></li>
</center>

			</ul>

            </div>






</form>





</div>








        </div>
	</div>
</div>






{%	endblock	%}



imagec/templates/navbar.html
<!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Bootstrap theme</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
              {% url 'home' as home %}
              {% url 'about' as about %}
              {% url 'contact' as contact %}
            <li {% if request.path == home %} class="active" {% endif %} ><a href="{% url 'home' %}">Home</a></li>
            <li {% if request.path == about %} class="active" {% endif %} ><a href="{% url 'about' %}">About</a></li>
            <li {% if request.path == contact %} class="active" {% endif %}><a href="{% url 'contact' %}">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                {% if not request.user.is_authenticated %}
                <li><a href="{% url 'account_login' %}">Login</a></li>
                <li><a href="{% url 'account_signup' %}">Signup</a></li>
                {% else %}
                <li><a href="{% url 'account_logout' %}">Logout</a></li>
                {% endif %}


                <li><a href="{% url 'about' %}">My Profile</a></li>

                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

imagec/templates/newhome.html
<h1>hello</h1>

imagec/templates/post_detail.html
{% extends 'base.html' %}
{% block content %}
 <div>
                 {% if user.is_authenticated %}
	 <h1>{{	user.post.Penname	}}</h1>
								<p>{{	user.post.text|linebreaksbr	}}</p>

					<a	class="btn	btn-default" href="{% url 'post_edit'	%}">
						<span	class="glyphicon	glyphicon-pencil"></span></a>
{% endif %}


				</div>

{%	endblock	%}

imagec/templates/post_edit.html
{%	extends	'base.html'	%}

{%	block	content	%}
<div class="tb5">
	<div class="wrapper4">

				<form method="POST" class="form-signin2">
					<input name="csrfmiddlewaretoken" value="c6ajCibJnUXunuvK7RZWnrPiVt8ekVw4yqI5Z3Q8dL7IbeJeFeXeyrSkhVwQInzT" type="hidden">
								<p><label for="id_Penname">PenName:</label>

					<input id="id_Penname" maxlength="200" name="Penname"  type="text" required></p>
                             <br>

							<p><label for="id_AboutMe">AboutMe:</label>
				      <input id="id_AboutMe" maxlength="200" name="AboutMe"  type="text" required></p>

					<div class="row">
					  <input type="submit" class="action-button1 shadow animate blue" value="Save"  >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					  <!-- <input type="button" class="action-button1 shadow animate blue"  value="Skip" formnovalidate>-->
						<a href="{% url 'newhome' %}"><input type="button" class="action-button1 shadow animate blue"  value="Skip" formnovalidate></a>
					 </div>
								<!--<button type="submit" class="save	btn	btn-default">Save</button>
								<button type="submit" class="save	btn	btn-default">Skip</button>-->
				</form>
	</div>
</div>

{%	endblock	%}

imagec/templates/profile.html
{% extends 'base.html' %}


{%	block	content	%}
{{ user.username }}
{{ user.email }}

{% endblock %}

imagec/templates/signup1.html
{% extends 'base.html' %}

{%	block	content	%}
<div class="wrapper2">
    <form class="form-signin">
      <h2 class="form-signin-heading">SIGN UP</h2>

        <input type="text" class="form-control" name="phone" placeholder="Phone number" required="" autofocus="" />

      <input type="email" class="form-control" name="email" placeholder="Email Address" required="" autofocus="" />

      <input type="password" class="form-control" name="password" placeholder="password" required="" autofocus="" />

<input type="repassword" class="form-control" name="repassword" placeholder="confirm password" required=""/>

      <button class="btn btn-lg btn-primary btn-block" type="submit">SignUp</button>
    </form>
  </div>

{%	endblock	%}




imagec/templates/userprofile.html
{% extends 'base.html' %}

{%	block	content	%}
<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>Email: {{ user.email }}</p>
    <img src="{{ user.userprofile.image.url }}" width="240">
</div>
{%	endblock	%}


